- zmapi: v1.1.2, adds proxy_username and proxy_password to enable basic auth in combination with/instead of JWT authentication  - cam: v1.0.2, misc. fixes  - camwatch: misc. fixes

diff --git a/cam b/cam
--- a/cam
+++ b/cam
@@ -2,6 +2,9 @@
 
 shopt -s extglob
 
+version="1.0.2"
+release="20221001"
+
 declare -A camera
 
 username="admin"
@@ -9,22 +12,22 @@ password=""
 viewer="display"
 player="mpv"
 
-confdir="$HOME/.config/zmapi"
+confdir="${XDG_CONFIG_HOME:-$HOME/.config}/zmapi"
 config="cam.conf"
 
 if [ -f "$confdir/$config" ]; then
-	source  "$confdir/$config"
+    source  "$confdir/$config"
 else
-	echo "configuration file ($confdir/$config) missing"
-	echo "new file created, edit it and restart program"
-	echo <<-EOT > "$confdir/$config"
+    echo "configuration file ($confdir/$config) missing"
+    echo "new file created, edit it and restart program"
+    cat <<-EOT > "$confdir/$config"
 	camera=()
 	username=
 	password=
 	viewer=
 	player=
-	EOT
-	exit 1
+EOT
+    exit 1
 fi
 
 auth=$(echo -n "$username:$password"|base64)
@@ -121,268 +124,416 @@ declare -A video_hue=()
 declare -A video_sharpness=()
 
 is_json () {
-	jq -e . >/dev/null 2>&1 <<<"$@"
+    jq -e . >/dev/null 2>&1 <<<"$@"
 }
 
 cam_url () {
-	cam="$1"
-	echo -n "http://${username}:${password}@${camera[$cam]}"
+    cam="$1"
+    echo -n "http://${username}:${password}@${camera[$cam]}"
 }
 
 get () {
-	cam="$1"
-	cmd="$2"
-	curl -s "$headers" "$(cam_url $cam)${SDK[$cmd]}"
+    cam="$1"
+    cmd="$2"
+    curl -s "$headers" "$(cam_url $cam)${SDK[$cmd]}"
 }
 
 put () {
-	cam="$1"
-	cmd="$2"
-	data="$3"
-	curl -g -s "$headers" "$(cam_url $cam)${SDK[$cmd]}" -X PUT --data-raw "$(echo "$data")"
+    cam="$1"
+    cmd="$2"
+    data="$3"
+    curl -g -s "$headers" "$(cam_url $cam)${SDK[$cmd]}" -X PUT --data-raw "$(echo "$data")"
 }
 
 get_json () {
-	cam="$1"
-	command="$2"
-	jqq="$3"
-	if [ -z "$jqq" ]; then
-		jqq="."
-	fi
-	echo -n "$command CAM$cam (${camera[$cam]}): "
-	result=$(get "$cam" "$command")
-	if is_json "$result"; then
-		jq "$jqq"<<<"$result"
-	else
-		echo "$result"
-	fi
+    cam="$1"
+    command="$2"
+    jqq="$3"
+    if [ -z "$jqq" ]; then
+        jqq="."
+    fi
+    echo -n "$command CAM$cam (${camera[$cam]}): "
+    result=$(get "$cam" "$command")
+    if is_json "$result"; then
+        jq "$jqq"<<<"$result"
+    else
+        echo "$result"
+    fi
 }
 
 put_json () {
-	cam="$1"
-	command="$2"
-	data="$3"
-	jqq="$4"
-	if [ -z "$jqq" ]; then
-		jqq=".statusMessage"
-	fi
-	echo -n "$command CAM$cam (${camera[$cam]}): "
-	put "${cam}" "$command" "$data"|jq "$jqq"
+    cam="$1"
+    command="$2"
+    data="$3"
+    jqq="$4"
+    if [ -z "$jqq" ]; then
+        jqq=".statusMessage"
+    fi
+    echo -n "$command CAM$cam (${camera[$cam]}): "
+    put "${cam}" "$command" "$data"|jq "$jqq"
 }
 
 get_text () {
-	cam="$1"
-	echo -n "$command CAM$cam (${camera[$cam]}):"
-	get "$cam" "$command"|tr -cd "[:print:]\n\t"
-	echo
+    cam="$1"
+    echo -n "$command CAM$cam (${camera[$cam]}):"
+    get "$cam" "$command"|tr -cd "[:print:]\n\t"
+    echo
 }
 
 check_range () {
-	value="$1"
-	range=$(echo "$2"|tr ',' '|')
-	field="$3"
-	if [[ "$range" == "$2" ]]; then
-		min=$(echo "$2"|cut -d '-' -f 1)
-		max=$(echo "$2"|cut -d '-' -f 2)
-		if [[ "$min" == "$max" ]]; then
-			printf "$field: invalid range specification\n\n"
-			exit 1
-		else
-			if [[ $value -ge $min && $value -le $max ]]; then
-				return
-			fi
-		fi
-	else
-		if [[ "$value" == @($range) ]]; then
-			return
-		fi
-	fi
+    value="$1"
+    range=$(echo "$2"|tr ',' '|')
+    field="$3"
+    if [[ "$range" == "$2" ]]; then
+        min=$(echo "$2"|cut -d '-' -f 1)
+        max=$(echo "$2"|cut -d '-' -f 2)
+        if [[ "$min" == "$max" ]]; then
+            printf "$field: invalid range specification\n\n"
+            exit 1
+        else
+            if [[ $value -ge $min && $value -le $max ]]; then
+                return
+            fi
+        fi
+    else
+        if [[ "$value" == @($range) ]]; then
+            return
+        fi
+    fi
 
-	printf "$field: value '$value' invalid\n\n"
-	printf "allowed values: $2\n"
-	exit 1
+    printf "$field: value '$value' invalid\n\n"
+    printf "allowed values: $2\n"
+    exit 1
 }
 
 mutate () {
-	data="$1"
-	fieldtype="$2"
-	value="$3"
-	field=$(echo "$fieldtype"|cut -d ':' -f 1)
-	type=$(echo "$fieldtype"|cut -d ':' -f 2)
-	range=$(echo "$fieldtype"|cut -d ':' -f 3)
-	if [[ -n $range ]]; then
-		check_range "$value" "$range" "$field"
-	fi
-	case $type in
-		b|i)
-			jq ".$field=$value" <<<"$data"
-			;;
-		s)
-			jq ".$field=\"$value\"" <<<"$data"
-			;;
-		*)
-			jq ".$field=\"$value\"" <<<"$data"
-			;;
-	esac
+    data="$1"
+    fieldtype="$2"
+    value="$3"
+    field=$(echo "$fieldtype"|cut -d ':' -f 1)
+    type=$(echo "$fieldtype"|cut -d ':' -f 2)
+    range=$(echo "$fieldtype"|cut -d ':' -f 3)
+    if [[ -n $range ]]; then
+        check_range "$value" "$range" "$field"
+    fi
+    case $type in
+        b|i)
+            jq ".$field=$value" <<<"$data"
+            ;;
+        s)
+            jq ".$field=\"$value\"" <<<"$data"
+            ;;
+        *)
+            jq ".$field=\"$value\"" <<<"$data"
+            ;;
+    esac
 }
 
 help_command () {
-	command="$1"
-	declare -n opts="$command"
-	if [[ ${#opts[@]} -lt 1 ]]; then
-		printf "The $command command takes a single parameter and has no options\n"
-	else
-		printf "Available parameters for $command:\n\n"
-		for n in ${!opts[@]}; do printf "\t-$n\t$(echo "${opts[$n]}"| sed 's/:/ (type /;s/:/ values:/;s/$/\)/')\n";done
-	fi
-	echo
-	exit
+    command="$1"
+    declare -n opts="$command"
+    if [[ ${#opts[@]} -lt 1 ]]; then
+        printf "The $command command takes a single parameter and has no options\n"
+    else
+        printf "Available parameters for $command:\n\n"
+        for n in ${!opts[@]}; do printf "\t-$n\t$(echo "${opts[$n]}"| sed 's/:/ (type /;s/:/ values:/;s/$/\)/')\n";done
+    fi
+    echo
+    exit
 }
 
 
 config () {
-	cam="$1"
-	shift
-	command="$1"
-	shift
-	cam_ip="${camera[$cam]}"
-	declare -n opts="$command"
-	optstr="$(tr ' ' ':'<<<"${!opts[@]}"):H"
-	optlst="$(echo "${!opts[@]}"|sed -e 's/ /|/g')"
-	cc=$(get "$cam" "$command")
-	local OPTIND
-	while getopts "$optstr" OPTION; do
-		optset=1
-		case $OPTION in
-			H)
-				help_command $command
-				;;
-			@($optlst))
-				cc="$(mutate "$cc" "${opts[$OPTION]}" "$OPTARG")" || exit_with_error "$cc"
-				;;
-			*)
-				echo "unknown option $OPTION"
-				exit
-				;;
-		esac
-	done
-	if [ -v optset ];then
-		put_json "$cam" "$command" "$cc"
-	elif (declare -p $opts 2>&1>/dev/null) &&  [[ -z $optlst ]] && [[ -n $1 ]]; then
-		put_json "$cam" "$command" "\"$1\""
-	else
-		get_json "$cam" "$command"
-	fi
+    cam="$1"
+    shift
+    command="$1"
+    shift
+    cam_ip="${camera[$cam]}"
+    declare -n opts="$command"
+    optstr="$(tr ' ' ':'<<<"${!opts[@]}"):H"
+    optlst="$(echo "${!opts[@]}"|sed -e 's/ /|/g')"
+    cc=$(get "$cam" "$command")
+    local OPTIND
+    while getopts "$optstr" OPTION; do
+        optset=1
+        case $OPTION in
+            H)
+                help_command $command
+                ;;
+            @($optlst))
+                cc="$(mutate "$cc" "${opts[$OPTION]}" "$OPTARG")" || exit_with_error "$cc"
+                ;;
+            *)
+                echo "unknown option $OPTION"
+                exit
+                ;;
+        esac
+    done
+    if [ -v optset ];then
+        put_json "$cam" "$command" "$cc"
+    elif (declare -p $opts 2>&1>/dev/null) &&  [[ -z $optlst ]] && [[ -n $1 ]]; then
+        put_json "$cam" "$command" "\"$1\""
+    else
+        get_json "$cam" "$command"
+    fi
 }
 
 view () {
-	cam="$1"
-	cmd="$2"
-	$viewer "$(cam_url $cam)${SDK[$cmd]}" &
+    cam="$1"
+    cmd="$2"
+    $viewer "$(cam_url $cam)${SDK[$cmd]}" &
 }
 
 watch () {
-	cam="$1"
-	cmd="$2"
-	$player "rtsp://$username:$password@${camera[$cam]}${SDK[$cmd]}" &
+    cam="$1"
+    cmd="$2"
+    $player "rtsp://$username:$password@${camera[$cam]}${SDK[$cmd]}" &
 }
 
 is_ip () {
-	if [[ $1 =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]
-		then
-		#echo "IP is $1"
-		ret=0
-	else
-		#echo "$1 is not IP"
-      		ret=1
-   	fi
-	return $ret
+    if [[ $1 =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]
+        then
+        #echo "IP is $1"
+        ret=0
+    else
+        #echo "$1 is not IP"
+            ret=1
+    fi
+    return $ret
 }
 
 cam_for_ip () {
-	for cam in ${!camera[@]}; do
-		if [[ "${camera[$cam]}" == "$1" ]]; then
-			echo -n $cam
-			return
-		fi
-	done
-	exit_with_error "$1: unknown camera IP"
+    for cam in ${!camera[@]}; do
+        if [[ "${camera[$cam]}" == "$1" ]]; then
+            echo -n $cam
+            return
+        fi
+    done
+    exit_with_error "$1: unknown camera IP"
 }
 
 help () {
-	printf "Use: $(basename $0) command [camera|IP address|'all']\n\n"
-	printf "available commands:\n\n"
-	printf '%s\n' "${!SDK[@]}"|sort
-	exit
+    printf "$(basename $(readlink -f "$0")) version $version\n\n"
+    cat <<EOF
+    Use: $(basename $0) command [camera|IP address|'all']
+
+    A simple, shell (bash) based camera API CLI which, together with a watchdog
+    (camwatch) can be used to keep a flock of IP cameras up and running without
+    having to deal with those clunky web interfaces.
+
+    This tool is specific to (XiongMai-based) cameras using the 'NetSDK' API and
+    will need to be adapted to other camera types.
+
+    INSTALLATION
+
+    Copy the scripts (zmapi, cam and camwatch) to a directory in the PATH. Either
+    copy and edit the configuration files (zmapi.conf, cam.conf and camwatch.conf)
+    to the \$HOME/.config/zmapi directory for the user who will executre these
+    scripts. If the configuration files are not present on first run the scripts
+    will create them with default values on the first run and abort, in that case
+    edit the created files before continuing.
+
+    Run zmapi and cam without parameters for an overview of the available commands,
+    alternatively have a look at the source for more insight. The available
+    commands are defined in the API (zmapi) or SDK (cam) arrays, this is also where
+    new commands can be added if new API endpoints are discovered.
+
+    COMMANDS
+
+EOF
+
+    printf '\t%s\n' "${!SDK[@]}"|sort
+
+    cat <<'EOF'
+
+    EXAMPLES
+
+    Show the time according to camera number 1:
+
+        $ cam 1 time
+        time CAM1 (192.168.5.10): "2021-04-09T15:02:48+02:00"
+
+    Set the time on all cameras to the current time:
+
+        $ cam all time $(date -Iseconds)
+        time CAM1 (192.168.5.10): "OK"
+        time CAM2 (192.168.5.11): "OK"
+        time CAM3 (192.168.5.12): "OK"
+        time CAM4 (192.168.5.13): "OK"
+        time CAM5 (192.168.5.14): "OK"
+        time CAM6 (192.168.5.15): "OK"
+        time CAM7 (192.168.5.16): "OK"
+
+    Reboot camera #7:
+
+        $ cam 7 reboot
+        reboot CAM7 192.168.5.16): "OK"
+
+    Show video encoding configuration for camera #1:
+
+        $ cam 1 vencode_main
+        vencode_main CAM1 (192.168.5.10): {
+          "id": 101,
+          "enabled": true,
+          "videoInputChannelID": 101,
+          "codecType": "H.264",
+          "h264Profile": "high",
+          "freeResolution": false,
+          "channelName": "CAM1",
+          "bitRateControlType": "VBR",
+          "resolution": "1920x1080",
+          "constantBitRate": 2048,
+          "frameRate": 10,
+          "keyFrameInterval": 50,
+          "expandChannelNameOverlay": [
+            {
+              "expandChannelName": "cam1",
+              "id": 1,
+              "enabled": false,
+              "regionX": 0,
+              "regionY": 0
+            },
+            {
+              "expandChannelName": "",
+              "id": 2,
+              "enabled": false,
+              "regionX": 0,
+              "regionY": 0
+            },
+            {
+              "expandChannelName": "",
+              "id": 3,
+              "enabled": false,
+              "regionX": 0,
+              "regionY": 0
+            },
+            {
+              "expandChannelName": "",
+              "id": 4,
+              "enabled": false,
+              "regionX": 0,
+              "regionY": 0
+            }
+          ],
+          "channelNameOverlay": {
+            "enabled": true,
+            "regionX": 0,
+            "regionY": 0
+          },
+          "datetimeOverlay": {
+            "enabled": true,
+            "regionX": 1,
+            "regionY": 1,
+            "dateFormat": "YYYY/MM/DD",
+            "timeFormat": 24,
+            "displayWeek": true,
+            "displayChinese": false
+          },
+          "deviceIDOverlay": {
+            "enabled": false,
+            "regionX": 0,
+            "regionY": 0
+          },
+          "textOverlays": ""
+        }
+
+    Show which video encoding parameters can be changed on camera #1:
+
+        $ cam 1 vencode_main -H
+        Available parameters for vencode_main:
+
+            -F	freeResolution (type b)
+            -t	bitRateControlType (type s)
+            -r	resolution (type s)
+            -p	h264Profile (type s)
+            -n	channelName (type s)
+            -k	keyFrameInterval (type i)
+            -f	frameRate (type i)
+            -e	enabled (type b)
+            -c	codecType (type s)
+            -b	constantBitrate (type i)
+
+    Set the channelName (the name shown in the bottom-right of the image) for camera #2 to WATCHTOWER:
+
+        $ cam 2 vencode_main -n WATCHTOWER
+        vencode_main CAM2 (192.168.5.11): "OK"
+
+    ...etc
+EOF
+    exit
 }
 
 exit_with_error () {
-	printf "ERROR: $@\n"
-	exit 1
+    printf "ERROR: $@\n"
+    exit 1
 }
 
 # ---------------------------------------------------
 
 if is_ip "$1"; then
-	cam=$(cam_for_ip "$1")    
-	parameters=( "$@" )
-	parameters[0]=$cam
-	set -- "${parameters[@]}"
+    cam=$(cam_for_ip "$1")    
+    parameters=( "$@" )
+    parameters[0]=$cam
+    set -- "${parameters[@]}"
 fi
 
 case $1 in
 
-	@($camlst))
-		cam_s=$1
-		cam_f=$1
-		shift
-		;;
-	all)
-		cam_s=1
-		cam_f=8
-		shift
-		;;
-	*)
-		printf "camera number, IP address or 'all' missing\n\n"
-		help
+    @($camlst))
+        cam_s=$1
+        cam_f=$1
+        shift
+        ;;
+    all)
+        cam_s=1
+        cam_f=8
+        shift
+        ;;
+    help)
+        help
+        exit
+        ;;
+    *)
+        exit_with_error "camera number, IP address or 'all' missing"
+        ;;
 esac
 
 if [[ -z $1 ]]; then
-	help
+    help
 else
-	command="$1"
-	shift
+    command="$1"
+    shift
 fi
 
 if ! test ${SDK[$command]+_}; then
-	printf "unknown command $command\n\n"
-	help
+    printf "unknown command $command\n\n"
+    help
 fi
 
 for cam in $(seq "$cam_s" "$cam_f");do
-	case "$command" in
-		load)
-			get_json "$cam" "$command" ".CPU.Usage"
-			;;
-		health|config|log)
-			get_text "$cam"
-			;;
-		reboot)
-			put_json "$cam" "$command" '{true}'
-			;;
-		snapshot)
-			view "$cam" "$command"
-			;;
-		view_main|view_sub)
-			watch "$cam" "$command"
-			;;
-		help)
-			help
-			;;
-		*)
-			config "$cam" "$command" "$@"
-			;;
-	esac
+    case "$command" in
+        load)
+            get_json "$cam" "$command" ".CPU.Usage"
+            ;;
+        health|config|log)
+            get_text "$cam"
+            ;;
+        reboot)
+            put_json "$cam" "$command" '{true}'
+            ;;
+        snapshot)
+            view "$cam" "$command"
+            ;;
+        view_main|view_sub)
+            watch "$cam" "$command"
+            ;;
+        help)
+            help
+            ;;
+        *)
+            config "$cam" "$command" "$@"
+            ;;
+    esac
 done
 
 exit
diff --git a/camwatch b/camwatch
--- a/camwatch
+++ b/camwatch
@@ -1,25 +1,27 @@
 #!/bin/bash
 
+version="1.0.1"
+release="20221001"
+
 declare -a monitors
 threshold=3
 
-confdir="$HOME/.config/zmapi"
+confdir="${XDG_CONFIG_HOME:-$HOME/.config}/zmapi"
 config="camwatch.conf"
 
 mon_stat_store="$confdir/mon_stat_store"
 
-
 if [ -f "$confdir/$config" ]; then
-        source  "$confdir/$config"
+    source  "$confdir/$config"
 else
-        echo "configuration file ($confdir/$config) missing"
-        echo "new file created, edit it and restart program"
-        echo <<-EOT > "$confdir/$config"
+    echo "configuration file ($confdir/$config) missing"
+    echo "new file created, edit it and restart program"
+    cat <<-EOT > "$confdir/$config"
 	monitors=()
-        threshold=3
+	threshold=3
 	mon_stat_store="$confdir/mon_stat_store"
-	EOT
-	exit 1
+EOT
+    exit 1
 fi
 
 declare -A mon_fps
@@ -31,27 +33,27 @@ declare -A cam_reboot
 if ! declare -p mon_stat 2>&1>/dev/null;then declare -A mon_stat;fi
 
 while read mon fps; do
-	mon_fps["$mon"]="$fps"
+    mon_fps["$mon"]="$fps"
 done <<<"$(zmapi monitors|jq -r '.[][]["Monitor_Status"]|[.MonitorId,.CaptureFPS] |join(" ")')"
 
 for mon in ${monitors[*]};do
-	if [[ ${mon_fps[$mon]} == "0.00" ]]; then
-		echo "$mon not capturing"
-		mon_stat[$mon]=$((${mon_stat[$mon]}+1))
-		if [ ${mon_stat[$mon]} -gt $threshold ]; then
-			echo "Monitor $mon above threshold"
-			cam_ip=$(zmapi monitor $mon|jq '.[].Monitor.Path'|grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}')
-			cam_reboot[$cam_ip]=1
-			mon_stat[$mon]=0
-		fi
-	else
-		mon_stat[$mon]=0
-	fi
+    if [[ ${mon_fps[$mon]} == "0.00" ]]; then
+        echo "$mon not capturing"
+        mon_stat[$mon]=$((${mon_stat[$mon]}+1))
+        if [ ${mon_stat[$mon]} -gt $threshold ]; then
+            echo "Monitor $mon above threshold"
+            cam_ip=$(zmapi monitor $mon|jq '.[].Monitor.Path'|grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}')
+            cam_reboot[$cam_ip]=1
+            mon_stat[$mon]=0
+        fi
+    else
+        mon_stat[$mon]=0
+    fi
 done
 
 declare -p mon_stat > $mon_stat_store
 
 for ip in ${!cam_reboot[*]};do
-	echo "rebooting cam $ip..."
-	cam "$ip" reboot
+    echo "rebooting cam $ip..."
+    cam "$ip" reboot
 done
diff --git a/zmapi b/zmapi
--- a/zmapi
+++ b/zmapi
@@ -1,135 +1,264 @@
 #!/bin/bash
 
+trap "trap_error" TERM
+trap "trap_clean" EXIT
+export TOP_PID=$$
+
+version="1.1.2"
+release="20221001"
+
 username=""
 password=""
 server=""
 
-confdir="$HOME/.config/zmapi"
+confdir="${XDG_CONFIG_HOME:-$HOME/.config}/zmapi"
 config="zmapi.conf"
 access_token="access.json"
 refresh_token="refresh.json"
+opt_netrc="--netrc-optional"
+netrc=""
 
 if [ -f "$confdir/$config" ]; then
-	source  "$confdir/$config"
+    source  "$confdir/$config"
+    if [ -n "$proxy_username" -a -n "$proxy_password" ]; then
+        machine="${server##http*://}"
+        machine="${machine%%/*}"
+        netrc=$(mktemp --tmpdir zmapi_XXXXXXXXXX)
+        echo "machine $machine login $proxy_username password $proxy_password" > "$netrc"
+        opt_netrc="--netrc-file $netrc"
+    fi
 else
-	echo "configuration file ($confdir/$config) missing"
-	echo "new file created, edit it and restart program"
-	echo <<-EOT > "$confdir/$config"
-	username=
-	password=
-	server=
-	EOT
-	exit 1
+    echo "configuration file ($confdir/$config) missing"
+    echo "new file created, edit it and restart program"
+    echo <<-EOT > "$confdir/$config"
+    # ZoneMinder username, password and server:
+    username=
+    password=
+    server=
+    # Reverse proxy credentials:
+    # proxy_username=
+    # proxy_password=
+EOT
+    exit 1
 fi
 
 declare -A API=(
-	[monitors]='monitors.json|G'
-	[sourcetypes]='monitors/sourceTypes.json|G'
-	[monitor]='monitors/${1}.json|G'
-	[daemonstatus]='monitors/daemonStatus/id:${1}/daemon:${2:-zmc}.json|G'
-	[daemoncontrol]='monitors/daemonStatus/id:${1}/command:${2}/daemon:${3}.json|G'
-	[status]='monitors/${1}.json|G|.monitor.Monitor_Status'
-	[alarm]='monitors/alarm/id:${1}/command:${2:-status}.json|G'
-	[login]='host/login.json|P'
-	[events]='events/index/${1}.json|G'
-	[console_events]='events/consoleEvents/${1}.json|G'
-	[states]='states.json|G'
-	[restart]='states/change/restart.json|P'
-	[stop]='states/change/stop.json|P'
-	[start]='states/change/start.json|P'
-	[zones]='zones.json|G'
-	[load]='host/getLoad.json|G'
-	[daemoncheck]='host/daemonCheck.json|G'
-	[getdiskpercent]='host/getDiskPercent.json|G'
-	[storage]='storage.json|G'
-	[servers]='servers.json|G'
-	[configs]='configs.json|G'
+    [monitors]='monitors.json|G'
+    [sourcetypes]='monitors/sourceTypes.json|G'
+    [monitor]='monitors/${1}.json|G'
+    [daemonstatus]='monitors/daemonStatus/id:${1}/daemon:${2:-zmc}.json|G'
+    [daemoncontrol]='monitors/daemonStatus/id:${1}/command:${2}/daemon:${3}.json|G'
+    [status]='monitors/${1}.json|G|.monitor.Monitor_Status'
+    [alarm]='monitors/alarm/id:${1}/command:${2:-status}.json|G'
+    [login]='host/login.json|P'
+    [events]='events/index/${1}.json|G'
+    [console_events]='events/consoleEvents/${1}.json|G'
+    [states]='states.json|G'
+    [restart]='states/change/restart.json|P'
+    [stop]='states/change/stop.json|P'
+    [start]='states/change/start.json|P'
+    [zones]='zones.json|G'
+    [load]='host/getLoad.json|G'
+    [daemoncheck]='host/daemonCheck.json|G'
+    [getdiskpercent]='host/getDiskPercent.json|G'
+    [storage]='storage.json|G'
+    [servers]='servers.json|G'
+    [configs]='configs.json|G'
 )
 
 get () {
-	cmd="$1"
-	shift
-	token="$1"
-	shift
-	path=$(echo "${API[$cmd]}"|cut -d '|' -f 1)
-	filter=$(echo "${API[$cmd]}"|cut -d '|' -f 3)
-	if [ -z "$filter" ]; then
-		filter='.'
-	fi
-	if [ $# -gt 0 ]; then
-		path="$(eval echo "$path")"
-	fi
-	(if [ $token == "null" ]; then
-		curl -s -XGET "$server/api/${path}"
-	else
-		curl -s -XGET "$server/api/${path}?token=$token"
-		fi)|jq -r "$filter"
+    cmd="$1"
+    shift
+    token="$1"
+    shift
+    path=$(echo "${API[$cmd]}"|cut -d '|' -f 1)
+    filter=$(echo "${API[$cmd]}"|cut -d '|' -f 3)
+    if [ -z "$filter" ]; then
+        filter='.'
+    fi
+    if [ $# -gt 0 ]; then
+        path="$(eval echo "$path")"
+    fi
+    (if [ "$token" == "null" ]; then
+        curl $opt_netrc -s -XGET "$server/api/${path}"
+    else
+        curl $opt_netrc -s -XGET "$server/api/${path}?token=$token"
+        fi)|jq -r "$filter" 2>/dev/null
 
 }
 
 post () {
-	cmd="$1"
-	shift
-	token="$1"
-	shift
-	data="$*"
-	path="${API[$cmd]%|P}"
-	if [ $token == "null" ]; then
-		curl -s -XPOST -d "$data" "$server/api/${path}"
-	else
-		curl -s -XPOST -d "$data" "$server/api/${path}?token=$token"
-	fi
+    cmd="$1"
+    shift
+    token="$1"
+    shift
+    data="$*"
+    path="${API[$cmd]%|P}"
+    if [ "$token" == "null" ]; then
+        curl $opt_netrc -s -XPOST -d "$data" "$server/api/${path}"
+    else
+        curl $opt_netrc -s -XPOST -d "$data" "$server/api/${path}?token=$token"
+    fi
 }
 
 get_token () {
-	atoken_expires=110
-	rtoken_expires=1400
-	access=$(find "$confdir" -name "$access_token" -mmin -$atoken_expires)
-	refresh=$(find "$confdir" -name "$refresh_token" -mmin -$rtoken_expires)
-	if [[ -n "$access" ]]; then
-		token=$(jq -r '.access_token' "$confdir/$access_token")
-	else
-		if [[ -n "$refresh" ]]; then
-			rtoken=$(jq -r '.refresh_token' "$confdir/$refresh_token")
-			token=$(post login $rtoken|tee "$confdir/$access_token"|jq -r '.access_token')
-		else
-			data="user=$username&pass=$password"
-			token=$(post login null "$data" |tee "$confdir/$refresh_token"|jq -r '.access_token')
-		fi
-	fi
+    if [ -n "$username" -a -n "$password" ]; then
+        atoken_expires=110
+        rtoken_expires=1400
+        access=$(find "$confdir" -name "$access_token" -mmin -$atoken_expires)
+        refresh=$(find "$confdir" -name "$refresh_token" -mmin -$rtoken_expires)
+        if [[ -n "$access" ]]; then
+            token=$(jq -r '.access_token' "$confdir/$access_token")
+        else
+            if [[ -n "$refresh" ]]; then
+                rtoken=$(jq -r '.refresh_token' "$confdir/$refresh_token")
+                token=$(post login $rtoken|tee "$confdir/$access_token"|jq -r '.access_token')
+            else
+                data="user=$username&pass=$password"
+                token=$(post login null "$data" |tee "$confdir/$refresh_token"|jq -r '.access_token')
+            fi
+        fi
+    else
+        token="null"
+    fi
 
-	echo -n $token
+    echo -n $token
 }
 
-help () {
-        printf "Use: $(basename $0) command [[parameter1] [[parameter2...]]]\n\n"
-        printf "available commands:\n\n"
-        printf '%s\n' "${!API[@]}"|sort
+cleanup () {
+    if [ -n "$netrc" -a -f "$netrc" ]; then
+        rm "$netrc"
+    fi
+}
+
+# echo error message to stderr and terminate main
+exit_with_error () {
+        echo -e "$(basename "$0"): $*" >&2
+
+        kill -s TERM "$TOP_PID"
+}
+
+trap_error () {
+    cleanup
+
+        exit 1
+}
+
+trap_clean () {
+    cleanup
+
         exit
 }
 
+help () {
+    printf "$(basename $(readlink -f "$0")) version $version\n\n"
+ 
+    cat <<- EOF
+    Use: $(basename $(readlink -f "$0")) command [[parameter1] [[parameter2...]]]
+
+    A simple, shell (bash) based ZoneMinder API CLI which, combined with a
+    camera control (cam) and watchdog (camwatch) can be used to keep a
+    ZoneMinder installation up and running without having to deal with those
+    clunky web interfaces.
+
+    The ZoneMinder API CLI script (zmapi) is independent of the camera control
+    scripts (cam and camwatch) and each can be used by itself.
+
+    INSTALLATION
+
+    Copy the scripts (zmapi, cam and camwatch) to a directory in the PATH.
+    Either copy and edit the configuration files (zmapi.conf, cam.conf and
+    camwatch.conf) to the $HOME/.config/zmapi directory for the user who will
+    executre these scripts. If the configuration files are not present on first
+    run the scripts will create them with default values on the first run and
+    abort, in that case edit the created files before continuing.
+
+    Run zmapi and cam without parameters for an overview of the available
+    commands, alternatively have a look at the source for more insight. The
+    available commands are defined in the API (zmapi) or SDK (cam) arrays, this
+    is also where new commands can be added if new API endpoints are
+    discovered.
+
+    COMMANDS
+
+EOF
+
+    printf '\t%s\n' "${!API[@]}"|sort
+
+    cat <<- 'EOF'
+
+    EXAMPLES
+
+    Show all monitors:
+
+        $ zmapi monitors
+        ...
+        ...lots of JSON output...
+
+    Show monitor #1:
+
+        $ zmapi monitor 1
+        ...
+        ...lots of JSON output...
+
+    Show monitor #1 status:
+
+        $ zmapi status 1
+        {
+          "MonitorId": "1",
+          "Status": "Connected",
+          "CaptureFPS": "10.00",
+          "AnalysisFPS": "10.00",
+          "CaptureBandwidth": "234455"
+        }
+
+    Show daemon status for monitor #1 (default shows zmc daemon status):
+
+        $ zmapi daemonstatus 1
+        {
+          "status": true,
+          "statustext": "'zmc -m 1' running since 21/04/09 01:06:46, pid = 12303"
+        }
+
+    Show zma status for that monitor:
+
+        $ zmapi daemonstatus 1 zma
+        {
+          "status": true,
+          "statustext": "'zma -m 1' running since 21/04/09 01:06:52, pid = 12314"
+        }
+
+    ...etc
+EOF
+
+    exit
+}
 
 token=$(get_token)
 
 cmd="$1"
 shift
 
-if ! test ${API[$cmd]+_}; then
-	printf "unknown command $cmd\n\n"
+if [ -z "$cmd" -o "$cmd" == "help" ]; then
 	help
-	exit 1
+    exit
+fi
+
+if ! test ${API[$cmd]+_}; then
+    printf "zmapi: unknown command '$cmd'\n"
+    exit 1
 fi
 
 method=$(echo "${API[$cmd]}"|cut -d '|' -f 2)
 
 case "$method" in
-	G)
-		get "$cmd" "$token" "$@"
-		;;
-	P)
-		post "$cmd" "$token" "$@"
-		;;
-	*)
-		printf "unknown method $method for command $cmd"
-		;;
+    G)
+        get "$cmd" "$token" "$@"
+        ;;
+    P)
+        post "$cmd" "$token" "$@"
+        ;;
+    *)
+        printf "unknown method $method for command $1"
+        ;;
 esac
